name: Create Release on Tag Push

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # 푸시된 태그 이름
          release_name: Release ${{ github.ref_name }} # 릴리스 이름
          body: |
            ## 변경 사항
            - 이 릴리스에 포함된 주요 변경 사항을 여기에 작성하세요.
          draft: false
          prerelease: false
